name: Python CI & Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with ruff
        run: |
          ruff check .

      - name: Test config loading
        run: |
          python -c "import toml; config = toml.load('config.toml'); print('✅ Config loaded successfully'); print(f'App title: {config[\"app\"][\"title\"]}')"

      - name: Test Streamlit app syntax
        run: |
          python -m py_compile app.py
          echo "✅ Python syntax check passed"
